### ISSUE TITLE
consider: putting your scripts for how to create these images on here

### ISSUE THREAD

**Issue by igalic** [goneri/bsd-cloud-image.org#1]
i mentioned potential other image variants to you on IRC, but maybe having your scripts online that would encourage people to create pull requests or open issues for other types of images they may need

also, a direct invitation on the website might do that

**Comment by goneri** [comment]
Thanks @igalic, The scripts are actually linked in About section:

- FreeBSD: https://github.com/virt-lightning/freebsd-cloud-images
- NetBSD: https://github.com/virt-lightning/netbsd-cloud-images
- OpenBSD: https://github.com/goneri/pcib

This being said, I totally agree I should add some more high-level documentation. I will keep the issue open until this is done.

**Comment by goneri** [comment]
And the automation is here: https://github.com/virt-lightning/cloud-init-bsd-testing it still has to be documented.

**Comment by goneri** [comment]
@igalic for the record, the OpenBSD images are now generated with a new tool https://github.com/hcartiaux/openbsd-cloud-image
