### ISSUE TITLE
OpenBSD 6.8 boot loader not working on Digital Ocean Droplets

### ISSUE THREAD

**Issue by justinnoor** [goneri/bsd-cloud-image.org#2]
Droplets are failing to boot on Digital Ocean with OpenBSD 6.8 images in region SFO3. The output in the recovery console indicates that the boot loader itself is not working. How do I troubleshoot this?

**Comment by goneri** [comment]
Hi @justinnoor,

Do you have a copy of the output? I imagine the name of the disk get changed, and because of that the bootload lose access to the root partition. Do you know if they use virtio?

**Comment by justinnoor** [comment]
Hi Goneri,

I’ll get the output to you ASAP

Thanks

**Comment by justinnoor** [comment]
Struggling to get the output - coupled with a wasteful exchange with DO. What should the name of the disk be when the bootloader attempts to access the root partition?

**Comment by goneri** [comment]
You should have something like this during the boot:

```
sd0 at scsibus2 targ 0 lun 0: <VirtIO, Block Device, >
sd0: 15360MB, 512 bytes/sector, 31457280 sectors
```

**Comment by justinnoor** [comment]
The console is literally just a blank screen. There's no way to scroll through it.

![openbsd_cloud_image_not_booting_0](https://user-images.githubusercontent.com/15651037/112768351-4a44e080-900b-11eb-9171-e5a03d39584e.png)

**Comment by justinnoor** [comment]
The console is literally just a blank screen. It's only accessible through the GUI in my DO portal. There's no way to scroll through it. 
![openbsd_cloud_image_not_booting_0](https://user-images.githubusercontent.com/15651037/112768705-cee42e80-900c-11eb-9b02-7f759105f7bc.png)

**Comment by goneri** [comment]
Excerpts from Justin Noor's message of March 28, 2021 5:20 pm:
> The console is literally just a blank screen. There's no way to scroll through it.
>

The console is on the first serial port, not on the VGA display.
-- 
    Gonéri Le Bouder

**Comment by justinnoor** [comment]
This is the only method that I know of for accessing the console on a Digital Ocean droplet. The console can only be accessed through the user portal of a Digital Ocean account. Thank you.

**Comment by goneri** [comment]
In this case, the best is to generate a new image with the serial console of, this would also give you the opportunity to adjust the boot device.

This is the repo and script I use to build the image: https://github.com/goneri/pcib/blob/master/build.sh

To disable the serial console, just remove this file: https://github.com/goneri/pcib/blob/master/plugins/os/openbsd/tasks/50-serial-console.sh

**Comment by goneri** [comment]
You can also give a try to the new tool that we use to build the image: https://github.com/hcartiaux/openbsd-cloud-image
