### ISSUE TITLE
FreeBSD: no console prompt after OS loaded

### ISSUE THREAD

**Issue by oneumyvakin** [goneri/bsd-cloud-image.org#6]
Tried FreeBSD 14 and 13 and faced the issue that after OS loaded there is no console prompt so it's impossible to login via console:

![image](https://github.com/goneri/bsd-cloud-image.org/assets/3854005/ceffa31f-d436-4ed0-9497-05e9478a42e8)

There is no such issue with official images from https://download.freebsd.org/ftp/releases/ISO-IMAGES/14.1/

As far as I know from Linux images, there is need to install and enable serial console service.

**Comment by goneri** [comment]
Thank @oneumyvakin  for the report. Are you using the serial or the video console?

**Comment by oneumyvakin** [comment]
Oh, I'd checked `virsh console vmname` and found that my script stuck in infinite loop. There is no any issue with console in the image.
Sorry for disturbing you!

**Comment by goneri** [comment]
No worries and thank you for the update!
